# Generated by Django 2.2 on 2020-07-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'ordering': ['-created_time'], 'verbose_name': '主页banner', 'verbose_name_plural': '主页banner'},
        ),
        migrations.AlterModelOptions(
            name='subpagebanner',
            options={'ordering': ['-created_time'], 'verbose_name': '二级页面banner', 'verbose_name_plural': '二级页面banner'},
        ),
    ]
