# Generated by Django 2.2 on 2020-07-04 08:42

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('type', models.IntegerField(choices=[('投诉', 1), ('建议', 2)], verbose_name='留言类型')),
                ('from_to', models.CharField(max_length=100, verbose_name='联系人')),
                ('tel', models.IntegerField(max_length=20, verbose_name='联系方式')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name_plural': '投诉与建议',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '网点',
                'verbose_name_plural': '网点',
            },
        ),
        migrations.CreateModel(
            name='WechatQrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('image', models.FileField(upload_to='wechat/', verbose_name='二维码')),
            ],
            options={
                'verbose_name': '二维码管理',
                'verbose_name_plural': '二维码管理',
            },
        ),
    ]
