# Generated by Django 2.2 on 2020-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='tel',
            field=models.IntegerField(verbose_name='联系方式'),
        ),
    ]
