# Generated by Django 2.2 on 2020-07-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('content', models.TextField(verbose_name='服务内容')),
            ],
            options={
                'verbose_name': '服务设置',
                'verbose_name_plural': '服务设置',
            },
        ),
    ]
