# Generated by Django 2.2 on 2020-07-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('content', models.TextField(verbose_name='服务内容')),
            ],
            options={
                'verbose_name': '特色服务',
                'verbose_name_plural': '特色服务',
            },
        ),
    ]
