# Generated by Django 2.2 on 2020-07-04 02:49

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200704_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeeperService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='服务内容')),
            ],
            options={
                'verbose_name': '管家服务',
                'verbose_name_plural': '管家服务',
            },
        ),
    ]
