# Generated by Django 2.2 on 2020-07-04 03:46

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='内容')),
                ('image', models.FileField(blank=True, help_text='该图片用于样式设置，无特别说明时，勿自行上传', null=True, upload_to='images_uploads/', verbose_name='图片上传')),
            ],
            options={
                'verbose_name': '可通风采',
                'verbose_name_plural': '可通风采',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': '公司简介', 'verbose_name_plural': '公司简介'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
