# Generated by Django 2.2 on 2020-07-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_companyculture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('image', models.FileField(help_text='正方形logo', upload_to='honor_image_luloads/', verbose_name='企业logo')),
            ],
            options={
                'verbose_name': '荣誉展示',
                'verbose_name_plural': '荣誉展示',
            },
        ),
    ]
