# Generated by Django 2.2 on 2020-07-05 13:26

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honor',
            options={'verbose_name': '企业荣誉', 'verbose_name_plural': '企业荣誉'},
        ),
        migrations.AddField(
            model_name='honor',
            name='content',
            field=DjangoUeditor.models.UEditorField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='honor',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='honor',
            name='image',
            field=models.FileField(blank=True, help_text='该图片用于样式设置，无特别说明时，勿自行上传', null=True, upload_to='images_uploads/', verbose_name='图片上传'),
        ),
    ]
