# Generated by Django 2.2 on 2020-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200705_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
