# Generated by Django 2.2 on 2020-07-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='客户类型')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='客户名称')),
                ('description', models.TextField(verbose_name='客户描述')),
                ('customer_logo', models.FileField(upload_to='customer_logo/', verbose_name='客户logo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Type', verbose_name='客户类型')),
            ],
            options={
                'verbose_name': '客户案例',
                'verbose_name_plural': '客户案例',
            },
        ),
    ]
